// apps/explorer/src/components/onboarding/ShortcutsModal.tsx
'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { Command, X, Keyboard } from 'lucide-react'
import { useAppStore } from '@/store/useAppStore'

interface ShortcutRow {
  keys: string[]
  label: string
}

interface ShortcutGroup {
  title: string
  rows: ShortcutRow[]
}

const GROUPS: ShortcutGroup[] = [
  {
    title: 'Navigation',
    rows: [
      { keys: ['⌘', '1'], label: 'Go to Camera' },
      { keys: ['⌘', '2'], label: 'Go to Chat' },
      { keys: ['⌘', 'B'], label: 'Collapse / expand sidebar' },
    ],
  },
  {
    title: 'Chat',
    rows: [
      { keys: ['⌘', 'K'], label: 'Start a new chat' },
      { keys: ['Esc'], label: 'Close menus & dialogs' },
    ],
  },
  {
    title: 'Help',
    rows: [
      { keys: ['?'], label: 'Open this shortcuts guide' },
    ],
  },
]

function KeyCap({ children }: { children: string }) {
  return (
    <kbd className="min-w-[26px] h-[26px] px-1.5 inline-flex items-center justify-center rounded-md border border-[var(--sp-border)] bg-[var(--sp-surface)] text-[12px] font-mono font-medium text-[var(--sp-text)] shadow-[0_1px_0_rgba(255,255,255,0.06)_inset]">
      {children}
    </kbd>
  )
}

export function ShortcutsModal() {
  const open = useAppStore((s) => s.shortcutsOpen)
  const close = useAppStore((s) => s.closeShortcuts)

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.15 }}
          className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md"
          onClick={close}
        >
          <motion.div
            initial={{ opacity: 0, y: 14, scale: 0.97 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.98 }}
            transition={{ type: 'spring', stiffness: 340, damping: 30 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-md rounded-[var(--sp-radius-lg)] border border-[var(--sp-border)] bg-[var(--sp-bg-1)]/95 shadow-[0_24px_70px_rgba(0,0,0,0.6)] overflow-hidden"
          >
            <div className="flex items-center gap-2.5 px-5 py-4 border-b border-[var(--sp-border)]">
              <div className="w-8 h-8 rounded-lg bg-[var(--sp-primary)]/15 flex items-center justify-center shrink-0">
                <Keyboard size={16} className="text-[var(--sp-primary)]" />
              </div>
              <h2 className="flex-1 font-heading text-[15px] font-semibold text-[var(--sp-text)]">
                Keyboard shortcuts
              </h2>
              <button
                onClick={close}
                aria-label="Close"
                className="w-8 h-8 rounded-lg flex items-center justify-center text-[var(--sp-text-faint)] hover:bg-[var(--sp-surface-hover)] hover:text-[var(--sp-text)] transition-colors"
              >
                <X size={16} />
              </button>
            </div>

            <div className="max-h-[60vh] overflow-y-auto px-5 py-4 flex flex-col gap-5 no-scrollbar">
              {GROUPS.map((group) => (
                <div key={group.title}>
                  <div className="text-[11px] font-semibold uppercase tracking-wider text-[var(--sp-text-faint)] mb-2">
                    {group.title}
                  </div>
                  <div className="flex flex-col gap-1.5">
                    {group.rows.map((row) => (
                      <div key={row.label} className="flex items-center justify-between gap-4 py-0.5">
                        <span className="text-[13.5px] text-[var(--sp-text-dim)]">{row.label}</span>
                        <div className="flex items-center gap-1 shrink-0">
                          {row.keys.map((k, i) => (
                            <span key={i} className="flex items-center gap-1">
                              <KeyCap>{k}</KeyCap>
                              {i < row.keys.length - 1 && (
                                <span className="text-[var(--sp-text-faint)] text-[11px]">+</span>
                              )}
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            <div className="flex items-center gap-1.5 px-5 py-3 border-t border-[var(--sp-border)] text-[11.5px] text-[var(--sp-text-faint)]">
              <Command size={12} />
              Press <KeyCap>?</KeyCap> anytime to bring this back up
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// apps/chat/src/components/common/ShortcutsModal.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import { X, Search, SquarePen, PanelLeft, SunMoon, Settings as SettingsIcon, MessageSquare } from 'lucide-vue-next'
import { useUiStore } from '@/stores/ui'
import { useChatStore } from '@/stores/chat'
import { useThemeStore } from '@/stores/theme'
import { SHORTCUTS } from '@/composables/useShortcuts'

const ui = useUiStore()
const chat = useChatStore()
const theme = useThemeStore()

const query = ref('')
const inputEl = ref<HTMLInputElement | null>(null)

// Reset + refocus the search field every time the palette opens, so it's
// never left showing a stale query from the last time it was used.
watch(
  () => ui.commandPaletteOpen,
  async (open) => {
    if (!open) return
    query.value = ''
    await nextTick()
    inputEl.value?.focus()
  },
)

interface QuickAction { id: string; label: string; icon: typeof SquarePen; run: () => void }
const actions = computed<QuickAction[]>(() => [
  { id: 'new', label: 'New chat', icon: SquarePen, run: () => chat.newConversation() },
  { id: 'sidebar', label: 'Toggle sidebar', icon: PanelLeft, run: () => ui.toggleSidebar() },
  { id: 'theme', label: 'Toggle theme', icon: SunMoon, run: () => theme.toggle() },
  { id: 'settings', label: 'Open settings', icon: SettingsIcon, run: () => { ui.settingsOpen = true } },
])

const filteredActions = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return actions.value
  return actions.value.filter((a) => a.label.toLowerCase().includes(q))
})

// Recent chats when the field is empty, filtered by title once you type —
// the same "search or jump" pattern ChatGPT/Claude's own Cmd+K palettes use.
const filteredChats = computed(() => {
  const q = query.value.trim().toLowerCase()
  const pool = chat.sortedConversations
  return (q ? pool.filter((c) => c.title.toLowerCase().includes(q)) : pool.slice(0, 6)).slice(0, 8)
})

const hasResults = computed(() => filteredActions.value.length > 0 || filteredChats.value.length > 0)

function close() {
  ui.commandPaletteOpen = false
}
function runAction(a: QuickAction) {
  a.run()
  close()
}
function openChat(id: string) {
  chat.selectConversation(id)
  close()
}
function onEnter() {
  if (filteredActions.value.length) runAction(filteredActions.value[0])
  else if (filteredChats.value.length) openChat(filteredChats.value[0].id)
}
</script>

<template>
  <Transition
    enter-active-class="transition duration-150 ease-out"
    enter-from-class="opacity-0"
    enter-to-class="opacity-100"
    leave-active-class="transition duration-100 ease-in"
    leave-to-class="opacity-0"
  >
    <div
      v-if="ui.commandPaletteOpen"
      class="fixed inset-0 z-[200] flex items-start justify-center bg-black/50 px-4 pt-[14vh] backdrop-blur-sm"
      @click.self="close"
    >
      <div
        v-motion
        :initial="{ opacity: 0, y: 12, scale: 0.97 }"
        :enter="{ opacity: 1, y: 0, scale: 1, transition: { duration: 180, ease: 'easeOut' } }"
        class="flex max-h-[70vh] w-full max-w-[480px] flex-col overflow-hidden rounded-2xl border border-[var(--sp-border)] bg-[var(--sp-bg-1)] shadow-2xl"
      >
        <!-- Search — doubles as a quick switcher (chats) and a command
             runner (actions), the same combined role Cmd+K plays in most
             modern AI chat apps. -->
        <div class="flex items-center gap-2.5 border-b border-[var(--sp-border)] px-4 py-3">
          <Search :size="15" class="shrink-0 text-[var(--sp-text-faint)]" />
          <input
            ref="inputEl"
            v-model="query"
            placeholder="Search chats or run a command…"
            class="w-full bg-transparent text-[13.5px] text-[var(--sp-text)] placeholder:text-[var(--sp-text-faint)] focus:outline-none"
            @keydown.enter="onEnter"
            @keydown.esc="close"
          />
          <button
            class="shrink-0 rounded-lg p-1 text-[var(--sp-text-faint)] hover:bg-white/[0.06] hover:text-[var(--sp-text)]"
            @click="close"
            aria-label="Close"
          >
            <X :size="16" />
          </button>
        </div>

        <div class="min-h-0 flex-1 overflow-y-auto p-2">
          <div v-if="filteredActions.length" class="mb-1">
            <p class="px-2.5 pb-1 pt-1.5 text-[10.5px] font-semibold uppercase tracking-wide text-[var(--sp-text-faint)]">Actions</p>
            <button
              v-for="a in filteredActions"
              :key="a.id"
              @click="runAction(a)"
              class="flex w-full items-center gap-2.5 rounded-xl px-2.5 py-2 text-left transition-colors hover:bg-white/[0.06]"
            >
              <span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-white/[0.06]">
                <component :is="a.icon" :size="14" class="text-[var(--sp-text-dim)]" />
              </span>
              <span class="text-[13px] font-medium text-[var(--sp-text)]">{{ a.label }}</span>
            </button>
          </div>

          <div v-if="filteredChats.length" class="mb-1">
            <p class="px-2.5 pb-1 pt-1.5 text-[10.5px] font-semibold uppercase tracking-wide text-[var(--sp-text-faint)]">
              {{ query.trim() ? 'Chats' : 'Recent' }}
            </p>
            <button
              v-for="c in filteredChats"
              :key="c.id"
              @click="openChat(c.id)"
              :class="[
                'flex w-full items-center gap-2.5 rounded-xl px-2.5 py-2 text-left transition-colors hover:bg-white/[0.06]',
                chat.activeId === c.id && 'bg-white/[0.04]',
              ]"
            >
              <span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-white/[0.06]">
                <MessageSquare :size="13" class="text-[var(--sp-text-dim)]" />
              </span>
              <span class="min-w-0 flex-1 truncate text-[13px] text-[var(--sp-text)]">{{ c.title }}</span>
            </button>
          </div>

          <p v-if="!hasResults" class="px-3 py-6 text-center text-[12px] text-[var(--sp-text-faint)]">No matches for "{{ query }}"</p>

          <!-- Full shortcut reference stays reachable underneath, so
               nothing that lived here before is lost. -->
          <div class="mt-1 border-t border-[var(--sp-border)] pt-1">
            <p class="px-2.5 pb-1 pt-1.5 text-[10.5px] font-semibold uppercase tracking-wide text-[var(--sp-text-faint)]">Keyboard shortcuts</p>
            <div
              v-for="s in SHORTCUTS"
              :key="s.label"
              class="flex items-center justify-between gap-3 rounded-xl px-2.5 py-1.5 text-[12.5px] text-[var(--sp-text-dim)]"
            >
              <span>{{ s.label }}</span>
              <span class="flex shrink-0 items-center gap-1">
                <kbd
                  v-for="k in s.keys"
                  :key="k"
                  class="rounded-md border border-[var(--sp-border)] bg-white/[0.04] px-1.5 py-0.5 text-[10.5px] font-medium text-[var(--sp-text)]"
                >
                  {{ k }}
                </kbd>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Transition>
</template>
